FROM oven/bun:1

WORKDIR /usr/src/app

COPY  ./packages ./packages
COPY bun.lock  ./bun.lock

COPY package.json ./package.json
COPY turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install


RUN bun run generate:db
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 8080

CMD ["bun", "start:backend"]

