FROM oven/bun:1

WORKDIR /usr/src/app

COPY package*.json ./

RUN bun install 

COPY . .

RUN bun run generate:db
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 8080

CMD ["bun", "start:backend"]

