name : Deployment of Backend

on:
  push:
    branches: [main]
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

                
            - name : Docker Login
              uses : docker/login-action@v2
              with :  
                    username : ${{ secrets.DOCKER_USERNAME }}
                    password : ${{ secrets.DOCKER_TOKEN }} 

            - name : Build and Push Docker Image
              uses : docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: pankajkumardev/backend-app:${{ github.sha }}
            
            - name: Deploy to Ec2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script : |
                  docker pull pankajkumardev/backend-app:${{ github.sha }}
                  docker stop backend-app || true
                  docker rm backend-app || true
                  docker run -d -e DATABASE_URL=${{secrets.DATABASE_URL}} --name backend-app -p 8080:8080 pankajkumardev/backend-app:${{ github.sha }}
                
